# Generated by Django 6.1 on 2026-09-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensaje',
            name='cantida',
        ),
        migrations.AddField(
            model_name='mensaje',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='mensaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='categoria',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
